#!/usr/bin/env Rscript
# Paper-style redraw from the corrected GSEA object; no new statistical test.
suppressPackageStartupMessages({library(ggplot2);library(patchwork);library(enrichplot);library(dplyr);library(ragg);library(svglite)})
argv<-commandArgs(TRUE)
if(length(argv)<2)stop('Usage: Rscript draw_Figure4g.R corrected_GSEA.rds output_stem')
gsea<-readRDS(argv[1]);out<-argv[2];dir.create(dirname(out),recursive=TRUE,showWarnings=FALSE)
ids<-c('KEGG_ALZHEIMERS_DISEASE','KEGG_CARDIAC_MUSCLE_CONTRACTION','KEGG_HUNTINGTONS_DISEASE','KEGG_OXIDATIVE_PHOSPHORYLATION','KEGG_PARKINSONS_DISEASE')
r<-as.data.frame(gsea@result);stopifnot(all(ids %in% r$ID))
cols<-setNames(c('#C52D2D','#858585','#00BF8C','#364F9A','#DFC7DF'),ids)
labels<-setNames(r$Description[match(ids,r$ID)],ids)
es<-bind_rows(lapply(ids,function(id){d<-enrichplot:::gsInfo(gsea,id);d$pathway<-id;d}))
es$pathway<-factor(es$pathway,levels=ids)
style<-theme_classic(base_size=8,base_family='Arial')+theme(text=element_text(face='bold'),axis.text=element_text(size=7,colour='black'),axis.title=element_text(size=8),axis.line=element_blank(),panel.border=element_rect(colour='black',fill=NA,linewidth=.4),plot.margin=margin(2,2,1,2))
p1<-ggplot(es,aes(x,runningScore,colour=pathway))+geom_line(linewidth=.35)+scale_color_manual(values=cols,breaks=ids,labels=labels)+scale_x_continuous(expand=expansion(mult=c(0,.003)))+labs(x=NULL,y='Enrichment Score')+style+theme(axis.text.x=element_blank(),axis.ticks.x=element_blank(),legend.position='inside',legend.position.inside=c(.995,.995),legend.justification=c(1,1),legend.background=element_blank(),legend.title=element_blank(),legend.text=element_text(size=6.2),legend.key.height=grid::unit(2.8,'mm'),legend.key.width=grid::unit(4,'mm'),legend.margin=margin(0,0,0,0))
ticks<-es[es$position==1,];ticks$track<-match(ticks$pathway,ids)
p2<-ggplot(ticks,aes(x,track,colour=pathway))+geom_linerange(aes(ymin=track-.4,ymax=track+.4),linewidth=.22)+scale_color_manual(values=cols,guide='none')+scale_x_continuous(limits=range(es$x),expand=expansion(mult=c(0,.003)))+theme_void()+theme(plot.margin=margin(0,2,0,2))
z<-sort(gsea@geneList,decreasing=TRUE);ranked<-data.frame(rank=seq_along(z),metric=as.numeric(z))
p3<-ggplot(ranked,aes(rank,metric))+geom_col(fill='#AAAAAA',width=1)+scale_x_continuous(expand=expansion(mult=c(0,.003)))+labs(x='Rank in Ordered Protein List',y='Ranked List Metric')+style+theme(plot.margin=margin(1,2,2,2))
p<-p1/p2/p3+plot_layout(heights=c(3.2,.75,1.6))
ggsave(paste0(out,'.png'),p,width=125,height=82,units='mm',dpi=600,device=ragg::agg_png,bg='white')
ggsave(paste0(out,'.pdf'),p,width=125,height=82,units='mm',device=cairo_pdf,bg='white')
ggsave(paste0(out,'.svg'),p,width=125,height=82,units='mm',device=svglite::svglite,bg='white')
write.csv(r[match(ids,r$ID),],paste0(out,'_source_data.csv'),row.names=FALSE)
write.csv(es,paste0(out,'_running_scores.csv'),row.names=FALSE)
write.csv(ranked,paste0(out,'_ranked_metric.csv'),row.names=FALSE)
cat('Five original manuscript pathways redrawn from corrected GSEA.\n')
