suppressPackageStartupMessages(library(dplyr))
argv <- commandArgs(TRUE)
for(x in parse(argv[1])) if(is.call(x) && identical(x[[1]],as.name('<-')) && is.symbol(x[[2]]) && identical(as.character(x[[2]]),'classify_go_terms'))eval(x)
z<-data.frame(ID=c('both_significant','RNA_only_significant','Protein_only_significant','RNA_only_returned','neither_significant','missing_FDR'),Count_RNA=c(5,10,3,4,2,1),Count_Protein=c(7,80,20,NA,3,NA),pvalue_RNA=c(.001,.002,.6,.001,.8,NA),pvalue_Protein=c(.003,.8,.001,NA,.9,NA),p.adjust_RNA=c(.01,.02,.8,.01,.9,NA),p.adjust_Protein=c(.03,.9,.01,NA,.95,NA))
x<-classify_go_terms(z,.05)
stopifnot(identical(x$SourceType,c('Common','RNA','Protein','RNA','Not significant','Not significant')))
stopifnot(identical(x$Count,c(12,10,20,4,NA_real_,NA_real_)))
stopifnot(identical(x$tested_in_both,c(TRUE,TRUE,TRUE,FALSE,TRUE,FALSE)))
stopifnot(sum(x$significant_RNA|x$significant_Protein)==4,sum(x$significant_in_both)==1)
stopifnot(isTRUE(all.equal(x$joint_FDR[x$tested_in_both],p.adjust(x$joint_p[x$tested_in_both],'BH'))))
stopifnot(x$display_FDR[2]==.02,x$display_FDR[3]==.01)
cat('PASS: asymmetric significance; shared criterion; side-specific Count/FDR; all-common-tested BH family; missing values.\n')
if(length(argv)>1){
 new<-read.delim(argv[2]); old<-read.delim(argv[3]);ii<-match(new$ID,old$ID);stopifnot(!anyNA(ii),nrow(new)==nrow(old))
 for(col in c('pvalue_RNA','p.adjust_RNA','pvalue_Protein','p.adjust_Protein','Count_RNA','Count_Protein','joint_FDR'))stopifnot(isTRUE(all.equal(new[[col]],old[[col]][ii])))
 stopifnot(sum(new$significant_RNA)==66,sum(new$significant_Protein)==70,sum(new$significant_in_both)==5,sum(new$html_displayed)==131,sum(new$static_displayed)==30)
 stopifnot(sum(new$SourceType=='RNA')==61,sum(new$SourceType=='Protein')==65)
 h<-new[new$ID=='GO:0007599',];stopifnot(h$SourceType=='RNA',h$html_displayed,h$Count==h$Count_RNA)
 cat('PASS: real ID9/ID19 unchanged ORA statistics; 66 RNA/70 protein/5 shared/131 union; static cap30; hemostasis restored to RNA.\n')
}
